version: '3.1'

services:

  db:
    image: postgres:9.6.16
    restart: "no"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

